---
name: Consul-Dev

on:
  push:
    paths:
      - 'consul-dev/**'
      - '.github/workflows/consul-dev.yaml'

  schedule:
    # - cron: '30 * * * *'
    - cron: '22 7 * * *'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3

      - name: test dir
        run: ls -a consul-dev/
        
      - name: Create Issue on Lint failure.
        if: failure()
        uses: buluma/create-issue-action@v2.0.0
        with:
          title: consul-dev Lint Test Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: bug
          body: consul-dev Lint check failed for commit ${{github.sha}}

  build:

    runs-on: ubuntu-latest
    needs: yamllint

    steps:
    - uses: actions/checkout@v2
    - name: test dir
      run: ls -a consul-dev/

    - name: Run in Dir above
      run: cd consul-dev && ls -a

    - name: Where are we
      run: pwd && ls -a

    - name: Build the Docker image
      # run: docker build . --file jira/Dockerfile --tag docker-jira-test:$(date +%s)
      run: cd consul-dev && pwd && ls -a && docker build . --file Dockerfile --tag docker-consul-dev:$(date +%s)

    - name: Create Issue on Build failure.
      if: failure()
      uses: buluma/create-issue-action@v2.0.0
      with:
        title: consul-dev Build Failed
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: bug
        body: consul-dev build failed for commit ${{github.sha}}

  push_to_registry:
    name: Push Docker image to Docker Hub.
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: consul-dev/
          push: true
          tags: buluma/consul-dev:latest
