---
name: Elastalert

on:
  push:
    paths:
      - 'elastalert/**'
      - '.github/workflows/elastalert.yaml'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3

      - name: test dir
        run: ls -a elastalert/

  build:

    runs-on: ubuntu-latest
    needs: yamllint

    steps:
    - uses: actions/checkout@v2
    - name: test dir
      run: ls -a elastalert/

    - name: Run in Dir above
      run: cd elastalert && ls -a

    - name: Build the Docker image
      run: docker build . --file elastalert/Dockerfile --tag docker-elastalert-test:$(date +%s)
