---
name: Mattermost

on:
  push:
    paths:
      - 'mattermost/**'
      - '.github/workflows/mattermost.yaml'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3

      - name: test dir
        run: ls -a mattermost/

      - name: Create Issue on Lint failure.
        if: failure()
        uses: buluma/create-issue-action@v2.0.0
        with:
          title: Mattermost Lint Test Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: bug
          body: Mattermost Lint check failed for commit ${{github.sha}}

  build:

    runs-on: ubuntu-latest
    needs: yamllint

    steps:
    - uses: actions/checkout@v2
    - name: test dir
      run: ls -a mattermost/

    - name: Run in Dir above
      run: cd mattermost && ls -a

    - name: Where are we
      run: pwd && ls -a

    - name: Build the Docker image
      # run: docker build . --file mattermost/Dockerfile --tag docker-mattermost-test:$(date +%s)
      run: cd mattermost && pwd && ls -a && docker build . --file Dockerfile --tag docker-mattermost-test:$(date +%s)

    - name: Create Issue on Build failure.
      if: failure()
      uses: buluma/create-issue-action@v2.0.0
      with:
        title: Mattermost Build Failed
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: bug
        body: Mattermost build failed for commit ${{github.sha}}
